web/config/routes.rb
Rails.application.routes.draw do
  get 'api/:name', to: 'api#execute'
  resources :endpoints
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

web/app/models/endpoint.rb
require 'net/http'

class Endpoint < ApplicationRecord

    before_save :compile_wasm!

    def compile_wasm!
        uri = URI('http://compiler:4000/compile')
        body = {
            id: self.name,
            source: self.source_code,
        }
        res = Net::HTTP.post(uri, body.to_json, "Content-Type" => "application/json")
        puts res
    end
end

web/app/controllers/api_controller.rb
require "extism"
require "json"

class ApiController < ApplicationController
  def execute
    name = params[:name]
    endpoint = Endpoint.find_by_name!(name)
    result = call_plugin endpoint
    puts "Result:"
    puts(result)
    resp = result["response"]
    status = resp["status"]
    slip = resp["sleep_for"]
    sleep slip if slip
    (resp["additional_headers"] || {}).each do |k, v|
      response.set_header(k, v)
    end

    render inline: resp["body"], status: resp["status"], content_type: resp["content_type"]
  end

  private

  def call_plugin(endpoint)
    call_data = {
      method: request.method,
      path: request.path,
    }
    manifest = {
      # warning: this is not safe!
      :wasm => [{:path => "/wasm/#{endpoint.name}.wasm"}]
    }

    Extism.with_context do |ctx|
      plugin = ctx.plugin(manifest)
      Extism.set_log_file("/tmp/extism.log", "trace")
      call_resp = plugin.call("on_request", JSON.dump(call_data))
      JSON.parse(call_resp)
    end
  end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  before_action :set_endpoint, only: %i[ show edit update destroy ]

  # GET /endpoints or /endpoints.json
  def index
    @endpoints = Endpoint.all
  end

  # GET /endpoints/1 or /endpoints/1.json
  def show
  end

  # GET /endpoints/new
  def new
    @endpoint = Endpoint.new
  end

  # GET /endpoints/1/edit
  def edit
  end

  # POST /endpoints or /endpoints.json
  def create
    @endpoint = Endpoint.new(endpoint_params)

    respond_to do |format|
      if @endpoint.save
        format.html { redirect_to endpoint_url(@endpoint), notice: "Endpoint was successfully created." }
        format.json { render :show, status: :created, location: @endpoint }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endpoints/1 or /endpoints/1.json
  def update
    respond_to do |format|
      if @endpoint.update(endpoint_params)
        format.html { redirect_to endpoint_url(@endpoint), notice: "Endpoint was successfully updated." }
        format.json { render :show, status: :ok, location: @endpoint }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endpoints/1 or /endpoints/1.json
  def destroy
    @endpoint.destroy

    respond_to do |format|
      format.html { redirect_to endpoints_url, notice: "Endpoint was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endpoint
      @endpoint = Endpoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def endpoint_params
      params.require(:endpoint).permit(:name, :source_code)
    end
end

web/app/helpers/api_helper.rb
module ApiHelper
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/endpoints_helper.rb
module EndpointsHelper
end

web/app/views/endpoints/_endpoint.html.erb
<div id="<%= dom_id endpoint %>">
  <p>
    <strong>Name:</strong>
    <%= endpoint.name %>
  </p>

  <p>
    <strong>Source code:</strong>
    <%= endpoint.source_code %>
  </p>

</div>

web/app/views/endpoints/_form.html.erb
<%= form_with(model: endpoint) do |form| %>
  <% if endpoint.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(endpoint.errors.count, "error") %> prohibited this endpoint from being saved:</h2>

      <ul>
        <% endpoint.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :source_code, style: "display: block" %>
    <%= form.text_area :source_code,  :rows => 40, :cols => 120  %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

web/app/views/endpoints/edit.html.erb
<h1>Editing endpoint</h1>

<%= render "form", endpoint: @endpoint %>

<br>

<div>
  <%= link_to "Show this endpoint", @endpoint %> |
  <%= link_to "Back to endpoints", endpoints_path %>
</div>

web/app/views/endpoints/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Endpoints</h1>

<div id="endpoints">
  <% @endpoints.each do |endpoint| %>
    <%= render endpoint %>
    <p>
      <%= link_to "Show this endpoint", endpoint %>
    </p>
  <% end %>
</div>

<%= link_to "New endpoint", new_endpoint_path %>

web/app/views/endpoints/new.html.erb
<h1>New endpoint</h1>

<%= render "form", endpoint: @endpoint %>

<br>

<div>
  <%= link_to "Back to endpoints", endpoints_path %>
</div>

web/app/views/endpoints/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @endpoint %>

<div>
  <%= link_to "Edit this endpoint", edit_endpoint_path(@endpoint) %> |
  <%= link_to "Back to endpoints", endpoints_path %>

  <%= button_to "Destroy this endpoint", @endpoint, method: :delete %>
</div>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apitester</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>